# Path
fish_add_path $ANDROID_HOME/tools
fish_add_path $ANDROID_HOME/tools/bin
fish_add_path $ANDROID_HOME/platform-tools
fish_add_path /usr/local/opt/node@14/bin
fish_add_path /usr/local/share/npm/bin
fish_add_path /usr/local/mysql/bin
fish_add_path /Library/Frameworks/Python.framework/Versions/2.7/bin
fish_add_path /usr/local/bin
fish_add_path /usr/local/sbin
fish_add_path /opt/local/bin
fish_add_path /opt/local/sbin
fish_add_path /opt/homebrew/bin
fish_add_path $HOME/bin
fish_add_path $HOME/.bin
fish_add_path $HOME/.local/bin
fish_add_path $HOME/.yarn/bin
fish_add_path $HOME/.cargo/bin
fish_add_path /Applications/Postgres.app/Contents/Versions/latest/bin
fish_add_path $HOME/Library/Python/3.7/bin
fish_add_path $HOME/.cargo/env
fish_add_path $HOME/.tmux/plugins/tmuxifier/bin
fish_add_path $HOME/Git/sourcekit-lsp/.build/debug
fish_add_path $HOME/development/flutter/bin
